import type { Locale } from "./i18n";

// Shared analysis vocabulary. Provider names, driver codes and units stay unchanged.
const thai = {
  "Telemetry axis": "แกนกราฟข้อมูลการขับขี่",
  "Distance (m)": "ระยะทาง (เมตร)",
  "Time (s)": "เวลา (วินาที)",
  "FastF1 distance (m)": "ระยะทาง FastF1 (เมตร)",
  "Distance is unavailable or incomplete for one or more selected drivers. Use time; older artifacts need a worker refresh.": "ข้อมูลระยะทางของนักขับที่เลือกบางคนไม่มีหรือไม่ครบ กรุณาใช้แกนเวลา ไฟล์เก่าต้องรอ worker สร้างใหม่",
  "Drag to zoom all traces together. Distance uses FastF1's computed lap-distance channel, not exact GPS position. No distance is calculated in the browser.": "ลากเพื่อซูมกราฟทั้งหมดพร้อมกัน ระยะทางใช้ค่าภายในรอบที่ FastF1 คำนวณ ไม่ใช่ตำแหน่ง GPS แบบแม่นยำ และเว็บไม่คำนวณระยะทางเพิ่มเอง",
  "Championship points": "คะแนนแชมป์โลก", "Pace vs consistency": "เพซเทียบความสม่ำเสมอ", "OPEN DRIVER OVERVIEW TABLE": "เปิดตารางภาพรวมนักขับ", "Driver": "นักขับ", "Drivers": "นักขับ", "Team": "ทีม", "Points": "คะแนน", "Best finish": "อันดับดีที่สุด", "Avg finish": "อันดับเฉลี่ย", "Valid sessions": "เซสชันที่มีข้อมูล", "Median pace": "ค่ากลางเวลารอบ", "Consistency": "ความสม่ำเสมอ", "SEASON FORM": "ผลงานตลอดฤดูกาล", "POSITION · LOWER IS BETTER": "อันดับ · ค่ายิ่งต่ำยิ่งดี", "SESSION RESULTS · PROVISIONAL WHEN INCOMPLETE": "ผลเซสชัน · เป็นข้อมูลเบื้องต้นหากยังไม่ครบ", "SESSIONS": "เซสชัน", "DRIVERS ·": "นักขับ ·", "OVERVIEW": "ภาพรวม", "TYRE PERFORMANCE": "ประสิทธิภาพยาง", "BACK": "ท้ายแถว", "POINTS": "คะแนน",
  "No drivers selected for the overview.": "ยังไม่ได้เลือกนักขับสำหรับภาพรวม", "No completed session results are available for this filter.": "ยังไม่มีผลเซสชันที่จบแล้วตรงกับตัวกรอง", "No validated lap samples are available for this comparison.": "ยังไม่มีข้อมูลรอบที่ผ่านเกณฑ์สำหรับการเปรียบเทียบนี้", "FastF1 tyre strategy artifact is not available for the selected Driver(s) yet.": "ยังไม่มีข้อมูลกลยุทธ์ยางของนักขับที่เลือก", "Stint pace samples are not available yet.": "ยังไม่มีข้อมูลเพซในแต่ละช่วงการใช้ยาง", "MEDIAN PACE · SEC": "ค่ากลางเวลารอบ · วินาที", "CONSISTENCY · STD DEV": "ความสม่ำเสมอ · ส่วนเบี่ยงเบนมาตรฐาน", "STINT MEDIAN · SEC": "ค่ากลางเวลาช่วงยาง · วินาที", "Stint pace": "เพซช่วงการใช้ยาง",
  "Finish": "อันดับเข้าเส้นชัย", "Event points": "คะแนนในเซสชัน", "Total points": "คะแนนรวม", "LAPS": "รอบ",
  "← DRIVERS DIRECTORY": "← รายชื่อนักขับ", "DRIVER ANALYSIS ·": "วิเคราะห์นักขับ ·", "POINTS ·": "คะแนน ·", "WINS": "ชนะ",
  "01 · RESULTS": "01 · ผลการแข่งขัน", "02 · PACE": "02 · เพซ", "03 · STRATEGY": "03 · กลยุทธ์", "04 · TELEMETRY": "04 · ข้อมูลการขับขี่",
  "classified sessions": "เซสชันที่มีอันดับอย่างเป็นทางการ", "P1 IS BEST · JOLPICA RESULTS": "P1 คืออันดับดีที่สุด · ผลจาก Jolpica",
  "SEASON TOTAL AFTER EACH SCORING SESSION": "คะแนนสะสมหลังแต่ละเซสชันที่มีคะแนน", "RACECRAFT": "การแข่งและการทำอันดับ",
  "POSITIVE = POSITIONS GAINED ·": "ค่าบวก = อันดับที่ขยับขึ้น ·", "FASTF1 POSITION DELTA": "ผลต่างอันดับจาก FastF1", "OVERTAKES MADE": "จำนวนครั้งที่แซง", "OVERTAKES LOST": "จำนวนครั้งที่ถูกแซง", "RACE CONTROL": "ประกาศควบคุมการแข่งขัน",
  "FASTF1 DATA ·": "ข้อมูล FastF1 ·", "valid laps ·": "รอบที่ผ่านเกณฑ์ ·", "telemetry samples": "จุดข้อมูลการขับขี่", "sessions ·": "เซสชัน ·", "snapshot ·": "ข้อมูลที่จัดเก็บ ·", "sessions indexed": "เซสชันที่มีในรายการ",
  "“—” means the provider has not returned a validated value for that field.": "“—” หมายถึงแหล่งข้อมูลยังไม่มีค่าที่ผ่านการตรวจสอบในช่องนั้น",
  "DRIVER": "นักขับ", "VS ANALYSIS · 2 DRIVERS": "เปรียบเทียบนักขับ 2 คน", "· RESULT REFERENCE ·": "· ผลการแข่งขันอ้างอิง ·", "DRIVERS · LAP-BY-LAP": "นักขับ · เปรียบเทียบรายรอบ", "drivers selected": "นักขับที่เลือก",
  "FASTF1 · VALIDATED ANALYSIS": "FastF1 · ผ่านการตรวจสอบ", "OPENF1 · PROVISIONAL CONTEXT": "OpenF1 · ข้อมูลประกอบเบื้องต้น", "PROVIDER DATA UNAVAILABLE": "ยังไม่มีข้อมูลจากแหล่งข้อมูล", "FASTF1 VALIDATED": "FastF1 ผ่านการตรวจสอบ", "FASTF1 PENDING": "รอผลจาก FastF1",
  "FASTF1 · VALIDATED ARTIFACT": "FastF1 · ข้อมูลผ่านการตรวจสอบ", "FASTF1 · PENDING": "รอผลวิเคราะห์จาก FastF1", "RESULT DATA UNAVAILABLE": "ยังไม่มีผลการแข่งขัน", "Validated data": "ข้อมูลที่ผ่านเกณฑ์", "LAP": "รอบ", "LAP TIME · SEC": "เวลารอบ · วินาที",
  "Session": "เซสชัน", "Circuit": "สนาม", "Status": "สถานะ", "Source": "แหล่งข้อมูล", "Lap": "รอบ", "Grid": "อันดับสตาร์ท", "Delta": "ผลต่าง", "Pos": "อันดับ",
  "ROUND": "สนามที่", "SEASON": "ฤดูกาล", "CIRCUIT": "สนาม", "SESSION": "เซสชัน", "SESSION TYPE": "ประเภทเซสชัน",
  "ALL ROUNDS": "ทุกสนาม", "ALL CIRCUITS": "ทุกสนามแข่ง", "ALL SESSION TYPES": "ทุกประเภท", "LATEST MATCH": "รายการล่าสุดที่ตรงกัน",
  "RACE": "แข่งขัน", "QUALIFYING": "รอบคัดเลือก", "SPRINT": "สปรินต์", "SPRINT QUALIFYING": "คัดเลือกสปรินต์", "PRACTICE 1": "ซ้อม 1", "PRACTICE 2": "ซ้อม 2", "PRACTICE 3": "ซ้อม 3",
  "RESET": "ล้างตัวเลือก", "APPLY FILTERS": "ใช้ตัวกรอง", "SHOW ALL": "แสดงทั้งหมด", "HIDE ALL": "ซ่อนทั้งหมด",
  "Choose a view": "เลือกข้อมูลที่ต้องการดู", "ANALYSIS CONTROLS": "ตัวเลือกการวิเคราะห์", "Defaults to the latest available session.": "เริ่มจากเซสชันล่าสุดที่มีข้อมูล",
  "PACE CONTEXT": "เปรียบเทียบเพซกับ", "TEAMMATE": "เพื่อนร่วมทีม", "TEAMMATE CONTEXT": "เทียบเพื่อนร่วมทีม", "SESSION FIELD": "นักขับในเซสชัน",
  "RESULTS": "ผลการแข่งขัน", "CHAMPIONSHIP": "แชมป์โลก", "PACE ANALYSIS": "วิเคราะห์เพซ", "STRATEGY": "กลยุทธ์", "CONDITIONS": "สภาพสนาม", "ADVANCED DATA": "ข้อมูลเชิงลึก", "DATA TABLE": "ตารางข้อมูล",
  "CLEAN-LAP MEDIAN": "ค่ากลางเวลารอบที่ผ่านเกณฑ์", "BEST LAP": "รอบเร็วที่สุด", "THEORETICAL BEST": "เวลาที่ดีที่สุดเชิงทฤษฎี", "CONSISTENCY": "ความสม่ำเสมอ", "DEGRADATION": "แนวโน้มเวลาต่อรอบ", "VALID LAPS": "รอบที่ผ่านเกณฑ์",
  "FASTEST LAP": "รอบเร็วที่สุด", "PACE GAP": "ส่วนต่างเวลารอบ", "VALID SAMPLES": "ข้อมูลที่ผ่านเกณฑ์", "best selected drivers": "รอบดีที่สุดของนักขับที่เลือก",
  "OPEN DATA TABLE": "เปิดตารางข้อมูล", "OPEN RACE FORM TABLE": "เปิดตารางผลการแข่งขัน", "OPEN POINTS TABLE": "เปิดตารางคะแนน", "OPEN RACECRAFT TABLE": "เปิดตารางอันดับที่เปลี่ยนไป",
  "AVERAGE FINISH": "อันดับเฉลี่ย", "BEST FINISH": "อันดับดีที่สุด", "POSITIONS GAINED": "อันดับที่ขยับขึ้น", "season result": "ผลในฤดูกาลนี้", "grid to finish": "จากสตาร์ทถึงเส้นชัย",
  "Race finishes": "อันดับเข้าเส้นชัย", "Points momentum": "คะแนนสะสม", "Grid to finish": "สตาร์ทถึงเส้นชัย", "Tyre stints": "ช่วงการใช้ยาง", "Track weather": "สภาพอากาศในสนาม", "Telemetry trace": "ข้อมูลการขับขี่", "Session record": "บันทึกเซสชัน",
  "Selected session pace": "เพซของเซสชันที่เลือก", "Selected session": "เซสชันที่เลือก",
  "JUMP TO": "ไปยัง", "Guide": "วิธีอ่าน", "Overview": "ภาพรวม", "Results": "ผลการแข่งขัน", "Pace": "เพซ", "Strategy": "กลยุทธ์", "Telemetry": "ข้อมูลการขับขี่", "Sessions": "เซสชัน",
  "START HERE": "เริ่มอ่านที่นี่", "How to read this driver": "วิธีอ่านข้อมูลนักขับ", "Read the story in order: result, pace, strategy, then the detailed trace.": "เริ่มจากผลการแข่งขัน เพซ กลยุทธ์ แล้วดูรายละเอียดการขับขี่",
  "Where did they finish?": "จบอันดับเท่าไร?", "Finish position and cumulative points show the season outcome.": "อันดับเข้าเส้นชัยและคะแนนสะสมบอกผลตลอดฤดูกาล",
  "How fast were they?": "ทำความเร็วได้แค่ไหน?", "Clean-lap pace and consistency show repeatable speed, not just one lap.": "เวลารอบที่ผ่านเกณฑ์และความสม่ำเสมอบอกความเร็วที่ทำซ้ำได้",
  "How did the tyres work?": "ยางทำงานอย่างไร?", "Stints show compound choice, lap count and degradation.": "แต่ละช่วงแสดงชนิดยาง จำนวนรอบ และแนวโน้มเวลาที่เปลี่ยนไป",
  "Where was time made?": "ทำเวลาได้จากจุดไหน?", "Speed, throttle, brake and gear appear only after FastF1 validation.": "แสดงความเร็ว คันเร่ง เบรก และเกียร์เมื่อผ่านการตรวจสอบจาก FastF1",
  "No completed Race or Sprint results are available for this driver.": "ยังไม่มีผลแข่งขันหรือสปรินต์ของนักขับคนนี้",
  "Championship points are not available for the completed scoring sessions yet.": "ยังไม่มีคะแนนของเซสชันที่จบแล้ว",
  "Grid position data is not available for this driver yet.": "ยังไม่มีข้อมูลอันดับสตาร์ทของนักขับคนนี้",
  "Tyre stint data is not available for the selected session.": "ยังไม่มีข้อมูลช่วงการใช้ยางของเซสชันที่เลือก",
  "Loading analysis for the selected filters…": "กำลังโหลดข้อมูลตามตัวกรอง…",
  "Choose a slot, then select a driver. Deep-dive charts use this pair.": "เลือกช่อง A หรือ B แล้วเลือกนักขับ กราฟจะเปรียบเทียบคู่นี้",
  "Select a driver": "เลือกนักขับ", "FIELD VISIBILITY": "นักขับในภาพรวม", "More display options": "ตัวเลือกการแสดงผลเพิ่มเติม",
  "Clean-lap pace excludes pit laps, deleted laps and laps that fail accuracy or track-status checks.": "เพซใช้เฉพาะรอบที่ผ่านเกณฑ์ ไม่รวมรอบเข้าพิต ออกพิต ถูกลบ หรือไม่ผ่านการตรวจความแม่นยำและสภาพสนาม",
  "Consistency measures lap-time variation; lower means more consistent. Theoretical best sums the best validated sectors, not an actual completed lap.": "ความสม่ำเสมอวัดการกระจายของเวลารอบ ค่ายิ่งต่ำยิ่งสม่ำเสมอ ส่วนเวลาที่ดีที่สุดเชิงทฤษฎีคือผลรวมเซกเตอร์ดีที่สุดที่ผ่านเกณฑ์ ไม่ใช่รอบที่ขับได้จริง",
  "Speed": "ความเร็ว", "Throttle": "คันเร่ง", "Brake": "เบรก", "Gear": "เกียร์", "Elapsed time (s)": "เวลาภายในรอบ (วินาที)", "On": "กด", "Off": "ไม่กด",
  "Drag to zoom all traces together. Times start at the first recorded sample of each lap.": "ลากเพื่อซูมกราฟทั้งหมดพร้อมกัน เวลาเริ่มที่ข้อมูลจุดแรกของแต่ละรอบ",
  "Telemetry needs valid timestamps to align the traces. No sample-index approximation is shown.": "ต้องมีเวลาในข้อมูลเพื่อจัดแนวกราฟ ระบบไม่ใช้ลำดับ sample แทนเวลา",
  "Not started": "ยังไม่เริ่ม", "Waiting for analysis": "รอผลวิเคราะห์", "Partial data": "ข้อมูลไม่ครบ", "No matching data": "ไม่พบข้อมูลที่ตรงกัน", "Data ready": "ข้อมูลพร้อม", "Could not load this page": "โหลดหน้านี้ไม่สำเร็จ",
  "Analysis becomes available after the session ends and its data is published.": "ผลวิเคราะห์จะพร้อมหลังเซสชันจบและมีการเผยแพร่ข้อมูล",
  "This session has no published analysis yet. Check again later or open an available session.": "ยังไม่มีผลวิเคราะห์ที่เผยแพร่สำหรับเซสชันนี้ ลองตรวจอีกครั้งภายหลังหรือเปิดเซสชันที่มีข้อมูล",
  "Some laps or channels are missing. Gaps are not measured values.": "บางรอบหรือบางช่องข้อมูลขาดหาย ช่วงว่างไม่ใช่ค่าที่วัดได้",
  "Try clearing the filters or choose another session.": "ลองล้างตัวกรองหรือเลือกเซสชันอื่น",
  "The page could not finish loading. Retry keeps your current URL and filters.": "หน้าเว็บโหลดไม่สำเร็จ ลองใหม่ได้โดยยังคง URL และตัวกรองเดิม",
  "Try again": "ลองใหม่", "Check again": "ตรวจอีกครั้ง", "Open an available session": "เปิดเซสชันที่มีข้อมูล", "View calendar": "ดูปฏิทิน", "Back to home": "กลับหน้าแรก",
  "Updated": "อัปเดต", "Update time unavailable": "ไม่มีเวลาอัปเดต", "Missing values are shown as —.": "เครื่องหมาย — หมายถึงยังไม่มีข้อมูล",
} as const;

export type AnalysisText = keyof typeof thai;
export function analysisText(locale: Locale, text: AnalysisText): string {
  return locale === "th" ? thai[text] : text;
}
