import { describe,expect,it } from "vitest";import { currentRound,deduplicateNews,getRound,rounds,standings,fallbackMetrics } from "./data";import { currentScheduleRound } from "./schedule";
describe("calendar context",()=>{it("selects an upcoming round",()=>{expect(currentRound(new Date("2026-08-20T00:00:00Z")).slug).toBe("zandvoort")});it("keeps a round for 48 hours after race",()=>{expect(currentRound(new Date("2026-07-06T12:00:00Z")).slug).toBe("silverstone")});it("has a deep link for every round",()=>{expect(rounds).toHaveLength(23);for(const round of rounds)expect(getRound(String(round.round))).toEqual(round)})});
describe("circuit geometry",()=>{it("keeps the Red Bull Ring visible when provider telemetry is degenerate",()=>{const round=rounds.find(item=>item.slug==="red-bull-ring");expect(round).toBeDefined();const coordinates=(round?.circuit.path.match(/-?\d+(?:\.\d+)?/g)??[]).map(Number);expect(new Set(coordinates).size).toBeGreaterThan(8);expect(Math.max(...coordinates)-Math.min(...coordinates)).toBeGreaterThan(40)})});
describe("session schedule context",()=>{it("opens the current-round window seven days before FP1",()=>{expect(currentScheduleRound(rounds,new Date("2026-02-28T00:00:00Z")).round).toBe(1);expect(currentScheduleRound(rounds,new Date("2026-03-20T00:00:00Z")).round).toBe(3)})});
describe("championship fallback",()=>{it("keeps a complete 22-driver grid",()=>{expect(standings).toHaveLength(22);expect(new Set(standings.map(driver=>driver.code)).size).toBe(22)})});
describe("provider fallback",()=>{it("never exposes fabricated metric values",()=>{expect(fallbackMetrics.every(metric=>metric.value==="—")).toBe(true)})});
describe("news source priority",()=>{it("keeps Autosport when both feeds publish the same story",()=>{const base={title:"Cadillac F1 team confirms new ownership plans",description:"",url:"https://example.com",publishedAt:"2026-08-21T10:00:00.000Z"};const result=deduplicateNews([{...base,id:"motorsport",source:"Motorsport.com",provider:"Motorsport.com"},{...base,id:"autosport",source:"Autosport",provider:"Autosport",publishedAt:"2026-08-21T09:00:00.000Z"}]);expect(result).toHaveLength(1);expect(result[0].provider).toBe("Autosport")})});

describe("circuit geometry coverage",()=>{it("keeps every circuit track non-degenerate",()=>{for(const round of rounds){const coordinates=(round.circuit.path.match(/-?\d+(?:\.\d+)?/g)??[]).map(Number);expect(new Set(coordinates).size).toBeGreaterThan(8);expect(Math.max(...coordinates)-Math.min(...coordinates)).toBeGreaterThan(40)}})});
function transformedPoint(point:[number,number],transform:string|undefined){if(!transform)return point;let result:[number,number]=point;const operations=[...transform.matchAll(/(matrix|translate|scale)\(([^)]+)\)/g)].reverse();for(const operation of operations){const values=operation[2].trim().split(/[ ,]+/).map(Number);if(operation[1]==="matrix"&&values.length===6)result=[values[0]*result[0]+values[2]*result[1]+values[4],values[1]*result[0]+values[3]*result[1]+values[5]];else if(operation[1]==="translate")result=[result[0]+values[0],result[1]+(values[1]??0)];else if(operation[1]==="scale")result=[result[0]*values[0],result[1]*(values[1]??values[0])]}return result}
function pathCoordinates(path:string){const tokens=path.match(/[a-zA-Z]|[-+]?(?:\d*\.\d+|\d+\.?)(?:e[-+]?\d+)?/gi)??[];const points:[number,number][]=[];const count:{[key:string]:number}={M:2,L:2,H:1,V:1,C:6,S:4,Q:4,T:2,A:7,Z:0};let index=0,command="M",x=0,y=0,startX=0,startY=0;while(index<tokens.length){if(/[a-zA-Z]/.test(tokens[index])){command=tokens[index++];if(command.toUpperCase()==="Z"){points.push([startX,startY]);x=startX;y=startY;command="";continue}}if(!command)continue;const upper=command.toUpperCase(),relative=command===command.toLowerCase(),size=count[upper];if(!size||index+size>tokens.length)break;const values=tokens.slice(index,index+size).map(Number);index+=size;const previousX=x,previousY=y;if(upper==="M"||upper==="L"||upper==="T"){x=(relative?x:0)+values[0];y=(relative?y:0)+values[1];points.push([x,y]);if(upper==="M"){startX=x;startY=y;command=relative?"l":"L"}}else if(upper==="H"){x=(relative?x:0)+values[0];points.push([x,y])}else if(upper==="V"){y=(relative?y:0)+values[0];points.push([x,y])}else if(upper==="C"){for(let offset=0;offset<6;offset+=2)points.push([(relative?previousX:0)+values[offset],(relative?previousY:0)+values[offset+1]]);x=(relative?previousX:0)+values[4];y=(relative?previousY:0)+values[5]}else if(upper==="S"||upper==="Q"){for(let offset=0;offset<4;offset+=2)points.push([(relative?previousX:0)+values[offset],(relative?previousY:0)+values[offset+1]]);x=(relative?previousX:0)+values[2];y=(relative?previousY:0)+values[3]}else if(upper==="A"){x=(relative?x:0)+values[5];y=(relative?y:0)+values[6];points.push([x,y])}}return points}
describe("reference circuit geometry",()=>{it("uses a current layout and marker for every circuit",()=>{expect(rounds).toHaveLength(23);for(const round of rounds){expect(round.circuit.path).toMatch(/^M/);if(round.slug!=="red-bull-ring")expect(round.circuit.pathTransform).toBeTruthy();expect(round.circuit.startPoint).toEqual(expect.objectContaining({x:expect.any(Number),y:expect.any(Number)}));const point=round.circuit.startPoint!;expect(point.x).toBeGreaterThanOrEqual(0);expect(point.x).toBeLessThanOrEqual(190);expect(point.y).toBeGreaterThanOrEqual(0);expect(point.y).toBeLessThanOrEqual(140)}})});
describe("circuit viewBox layout",()=>{it("keeps every track centered and inside the shared viewport",()=>{for(const round of rounds){const points=pathCoordinates(round.circuit.path).map(point=>transformedPoint(point,round.circuit.pathTransform));const xs=points.map(point=>point[0]);const ys=points.map(point=>point[1]);const minX=Math.min(...xs);const maxX=Math.max(...xs);const minY=Math.min(...ys);const maxY=Math.max(...ys);expect(minX).toBeGreaterThanOrEqual(8);expect(maxX).toBeLessThanOrEqual(182);expect(minY).toBeGreaterThanOrEqual(8);expect(maxY).toBeLessThanOrEqual(132);expect((minX+maxX)/2).toBeCloseTo(95,0);expect((minY+maxY)/2).toBeCloseTo(70,0);const marker=round.circuit.startPoint!;expect(marker.x).toBeGreaterThanOrEqual(minX-1);expect(marker.x).toBeLessThanOrEqual(maxX+1);expect(marker.y).toBeGreaterThanOrEqual(minY-1);expect(marker.y).toBeLessThanOrEqual(maxY+1)}})});
describe("Red Bull Ring geometry override",()=>{it("uses a rounded normalized Spielberg centerline and continuous sector path",()=>{const round=rounds.find(item=>item.slug==="red-bull-ring");expect(round?.circuit.pathTransform).toBeUndefined();expect(round?.circuit.path).toMatch(/^M 114\.07 117\.51/);expect(round?.circuit.path).toContain("Q 81.1 127 76.38 119.39");expect(round?.circuit.sectorPath).toBe("M 114.07 117.51 L 89.34 124.63 Q 81.1 127 76.38 119.39 L 62.22 96.56 Q 57.5 88.95 55.55 84.76");expect(round?.circuit.startPoint).toEqual({x:114.07,y:117.51})})});
